[pangolin]
endpoint = "wss://pangolin-rpc.darwinia.network"
signer = "//Alice"

[pangoro]
endpoint = "wss://pangoro-rpc.darwinia.network"
signer = "//Alice"

[relay]
# substrate-substrate bridger message relay lanes, default use `00000000`
lanes = ["72746c6c"]
# Auto start message relay, the default is false, because maybe the bridge hasn't been initialized yet;
# since init, there can change to true.
# WARNING: May be deleted in the future
auto_start = true
# (optional) The relay message signer, if not set will use [panglin.signer]
signer_pangolin = "//Alice"
# (optional) the relay message signer, if not set will use [pangoro.signer]
signer_pangoro = "//Alice"

# Transactions mortality period, in blocks. MUST be a power of two in [4; 65536] range.
# MAY NOT be larger than `BlockHashCount` parameter of the chain system module.
# Discuss: https://github.com/darwinia-network/bridger/pull/266#discussion_r705943606
#transactions_mortality = 256

[relay.prometheus_params]
no_prometheus = false
prometheus_host = "127.0.0.1"
prometheus_port = 9616